dbt_project:
  outputs:
    prd:
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      catalog: "workspace"
      schema: "case_ifood"
      threads: 1
      type: databricks
  target: prd