# .github/workflows/ci_cd.yml

name: CI/CD Pipeline for dbt Transformations

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run-dbt-on-databricks:
    runs-on: ubuntu-latest
    environment: prod
    
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DBT_DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      # Garante que o dbt não peça feedback
      DBT_SEND_ANONYMOUS_USAGE_STATS: "false"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: pip install dbt-core dbt-databricks

      - name: Debug Secrets
        run: |
          if [ -z "${{ env.DBT_DATABRICKS_TOKEN }}" ]; then
            echo "ERRO: O segredo DBT_DATABRICKS_TOKEN está VAZIO ou não foi definido."
            exit 1
          else
            echo "SUCESSO: O segredo DBT_DATABRICKS_TOKEN foi recebido."
            echo "Comprimento do token recebido: ${{ env.DBT_DATABRICKS_TOKEN && 'não-vazio' || 'vazio' }}"
          fi

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_project:
            target: prd
            outputs:
              prd:
                type: databricks
                host: ${{ env.DATABRICKS_HOST }}
                http_path: ${{ env.DATABRICKS_HTTP_PATH }}
                catalog: ifood_case
                schema: case
                threads: 1
                token: ${{ env.DATABRICKS_TOKEN }}
                type: databricks
                auth_type: token
          EOF

      - name: Test dbt connection
        run: dbt debug --project-dir dbt_project --debug

      - name: Run dbt models
        run: dbt run --project-dir dbt_project --no-version-check

      - name: Run dbt tests
        run: dbt test --project-dir dbt_project --no-version-check