# .github/workflows/ci_cd.yml

name: CI/CD Pipeline for dbt Transformations

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run-dbt-on-databricks:
    runs-on: ubuntu-latest
    environment: prod
    
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: pip install dbt-databricks

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_project:
            target: prod
            outputs:
              prod:
                type: databricks
                method: http
                host: ${{ env.DATABRICKS_HOST }}
                http_path: ${{ env.DATABRICKS_HTTP_PATH }}
                schema: default
                auth_type: oauth-m2m
                client_id: ${{ env.DATABRICKS_CLIENT_ID }}
          EOF

      - name: DEBUG - List all files recursively
        run: ls -R

      - name: Test dbt connection
        run: |
          cd dbt_project
          dbt debug

      - name: Run dbt test model
        run: |
          cd dbt_project
          dbt run --select hello_dbt