# .github/workflows/ci_cd.yml

name: CI/CD Pipeline for dbt Transformations

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run-dbt-on-databricks:
    runs-on: ubuntu-latest
    environment: prod
    
    env:
      # dbt-databricks usará estas variáveis para se autenticar via OIDC
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      # Precisamos passar o http_path para o profiles.yml
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: pip install dbt-databricks

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "dbt_project:\n  target: prod\n  outputs:\n    prod:\n      type: spark\n      host: ${{ env.DATABRICKS_HOST }}\n      http_path: ${{ env.DATABRICKS_HTTP_PATH }}\n      schema: default\n      auth_type: oauth-m2m\n      client_id: ${{ env.DATABRICKS_CLIENT_ID }}" > ~/.dbt/profiles.yml

      - name: Test dbt connection
        run: dbt debug --project-dir dbt_project

      - name: Run dbt test model
        run: dbt run --select hello_dbt --project-dir dbt_project