# .github/workflows/ci_cd.yml

name: Network Connectivity Test for Databricks

on:
  push:
    branches:
      - main

jobs:
  test-databricks-connection:
    runs-on: ubuntu-latest
    
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}

    steps:
      - name: Test network connection to Databricks endpoint
        # Usamos curl com -v (verbose) e --max-time para timeout
        # O objetivo é ver se conseguimos estabelecer uma conexão TLS/SSL
        # com o host do Databricks na porta 443.
        run: |
          echo "Tentando conectar a: ${{ env.DATABRICKS_HOST }}${{ env.DATABRICKS_HTTP_PATH }}"
          curl -v --max-time 30 ${{ env.DATABRICKS_HOST }}${{ env.DATABRICKS_HTTP_PATH }}