name: 'Databricks IaC Deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Apply Databricks Changes'
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      # --- PASSO DE INIT CORRIGIDO ---
      - name: 'Terraform Init'
        working-directory: ./terraform
        run: |
          # 1. Cria o arquivo de credenciais com o token que o Terraform precisa para o login.
          #    Esta é a forma mais garantida de autenticar em automações.
          echo 'credentials "app.terraform.io" { token = "${{ secrets.TF_API_TOKEN }}" }' > ~/.terraform.d/credentials.tfrc.json
          
          # 2. Executa o init, que agora vai encontrar o arquivo de login.
          terraform init
        
      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan
        working-directory: ./terraform
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}