name: 'Databricks IaC Deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Apply Databricks Changes'
    runs-on: ubuntu-latest
    
    env:
          TF_VAR_REPO_URL: ${{ secrets.REPO_URL }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        working-directory: ./terraform
        run: |
          mkdir -p ~/.terraform.d/
          echo 'credentials "app.terraform.io" { token = "${{ secrets.TF_API_TOKEN }}" }' > ~/.terraform.d/credentials.tfrc.json
          terraform init
        
      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform